name: Validate new commit messages
description: This action validates the format of commit messages for commits added since the last push.

runs:
  using: composite
  steps:

    - name: Get log of new commit messages
      id: log
      run: |
        git_log_output=$(git log --format=%s "${BASE_SHA:-$BEFORE_SHA}...${HEAD_SHA:-$GITHUB_REF}")
        
        echo "::notice::Changed files: $git_log_output"

        {
          echo "git_log_output<<EOF"
          echo "$git_log_output"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BEFORE_SHA: "${{ github.event.before }}"
      shell: bash
        
    - name: Validate new commit messages
      run: |
        echo "$GIT_LOG_OUTPUT" | while read -r line; do
          echo "Validating commit message on branch: '$line'"
          if [[ ! $line =~ ^((chore|dev|feature|fix|maintenance|merge|performance|refactor|release|revert): [a-z].*)$ ]]; then
            echo "Invalid commit message: '$line'"
            exit 1
          fi
        done
      env:
        GIT_LOG_OUTPUT: "${{ steps.log.outputs.git_log_output }}"
      shell: bash
