name: Validate new commit messages
description: This action validates the format of commit messages for commits added since the last push.

runs:
  using: composite
  steps:
    - name: Validate
      run: |
        # Equivalent to `git log ORIG_HEAD..HEAD`.
        # `github.event.before` is the last commit SHA before the push.
        git log --format=%s ${{ github.event.before }}..${{ github.sha }} | while read -r line; do
          echo "Validating commit message: '$line'"
          if [[ ! $line =~ ^((constraint|experiment|feature|fix|maintenance|merge|refactor): [a-z].*)$ ]]; then
            echo "Invalid commit message: '$line'"
            exit 1
          fi
          if [[ $line =~ ^(experiment: [a-z].*)$ ]]; then
            echo "Experiments should not be pushed upstream ('$line')"
            exit 1
          fi
        done
      # For custom actions, unlike workflows, we do need to specify the shell for run commands:
      shell: bash
