name: Amend hosts

on:
  push:
    branches:
      - dev

jobs:
  amend-hosts:
    name: Amend hosts
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository - this is required because the action is local.
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Amend hosts file (ip)
        uses: ./hosts-entry
        with:
          host: example.local
          ip: 127.0.0.2

      - name: Amend hosts file (cname)
        uses: ./hosts-entry
        with:
          host: example.local
          cname: example.com
          hosts-file: /etc/hosts1

  print-hosts:
    name: Print hosts
    runs-on: ubuntu-latest
    needs:
      - amend-hosts
    steps:

      - name: Print hosts file
        run: cat /etc/hosts

