name: Capitalize string

on:
  push:
    branches:
      - dev

jobs:
  capitalize-string:
    name: Capitalize string
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository and fetch its full log history.
      # https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: capitalization
        name: Change string case
        uses: ./change-string-case
        with:
          input: TEST input Value

      - id: print
        run: echo ${{ steps.capitalization.outputs.capitalized }}
